### ISSUE TITLE
Create backend tickets for project

### ISSUE THREAD

**Issue by irithsharma** [passiondynamics/cast-le#9]
**Points:** 2

**TODOs:**
- [ ] Make a ticket for each of the items listed in the notes

**Description:** Setting up all the tickets on our project board, making sure they're ready to be picked up.

**Notes:**
```
Python backend, React frontend

- Backend:
  - Generating challenges:
    - Connect to TMDB API
    - Retrieve movies from API
      - Get movie list
    - Retrieve data from API for movie
      - Get actors for movie
      - Calculate appropriate 4 actors for movie
      - Getting pictures
    - Making sure this movie isn't a repeat (see database)
    - Assign movie to next date
  - Database:
    - Storing the movie in the database
    - Fields:
      - (P) Movie ID (TMDB)
      - Date this applies to
      - Movie name
      - Actor names (4)
      - Actor images (4)
      - Possible answers
      - Hints
  - Live:
    - Retrieve current day's from db and return to frontend
  - Hint options:
    - Year
    - Director
    - Awards
- Frontend:
  - https://www.figma.com/file/wJRV4jNc2wOMOW3l6zQMVf/Cast-le?type=design&node-id=2-2&mode=design&t=Q3qG1HeAdHoizscJ-0
  - Basic layout (works on your screen)
  - Flexible layout (works on most screens)
  - Loading images
  - Inputs (text box and button)
  - Prepare for single entrypoint to backend (to get current day's data and insert), use dummy data
- Connecting backend to frontend:
  - Plug in backend (do the HTTP request to the backend)
  - Performance tests
- Infrastructure/hosting:
  - Resources:
    - Database (DynamoDB)
    - Frontend (S3 bucket, Route53/Cloudflare)
    - Backend (Lambda)
  - Manually setting up initial version/release
  - Automatically deploying changes through pipeline

Tasks/tickets:

Extra considerations:
- Movies w/ sequels or ones that have the same 4 popular actors
- Do alternative titles contain sequel titles and/or titles in different languages?
```
